
services:
  eureka:
    image: ghcr.io/ngolik/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    image: ghcr.io/ngolik/api-gateway:latest
    container_name: api-gateway
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    ports:
      - "8080:8080"

  auth-service:
    image: ghcr.io/ngolik/auth-service:latest
    container_name: auth-service
    depends_on:
      eureka:
        condition: service_started
      api-gateway:
        condition: service_started
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    ports:
      - "8081:8081"

volumes:
  auth_db_data:
