server:
  port: 8081
  servlet:
    context-path: /auth/

management:
  endpoints:
    web:
      base-path: /service
      exposure:
        include: health

logging:
  level:
    root: INFO
    com.softeq: DEBUG
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_AUTH_HOST}:${DB_AUTH_PORT}/${DB_AUTH_NAME}
    username: ${DB_AUTH_USER}
    password: ${DB_AUTH_PASSWORD}
    driver-class-name: org.postgresql.Driver
    database: postgresql
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:/liquibase/master.xml
    enabled: true
    url: jdbc:postgresql://${DB_AUTH_HOST}:${DB_AUTH_PORT}/${DB_AUTH_NAME}
    user: ${DB_AUTH_USER}
    password: ${DB_AUTH_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    non-secure-port: 8081
    prefer-ip-address: true
    ip-address: 192.168.0.80

aws:
  region: eu-west-1
  cognito:
    user-pool-id: eu-west-1_SO2QlXsQe