server:
  port: 8081
  servlet:
    context-path: /auth/

management:
  endpoints:
    web:
      base-path: /service
      exposure:
        include: health

logging:
  level:
    root: INFO
    com.softeq: DEBUG
    com.zaxxer.hikari: INFO
    org.hibernate: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework: INFO
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.datasource: DEBUG

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    database: postgresql
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/liquibase/master.xml
    enabled: true
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASS}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    non-secure-port: 8081

aws:
  region: eu-west-1
  cognito:
    user-pool-id: eu-west-1_SO2QlXsQe