spring:
  application:
    name: AUTH-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081
  servlet:
    context-path: /auth/rest/

management:
  endpoints:
    web:
      base-path: /service
      exposure:
        include: health

logging:
  level:
    root: INFO
    com.softeq: DEBUG
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework: INFO