name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Get DB Credentials from AWS Parameter Store
        run: |
          echo "Fetching DB credentials from AWS Parameter Store..."
          echo "DB_USER=$(aws ssm get-parameter --name '/DB_USER' --with-decryption --query 'Parameter.Value' --output text)" >> $GITHUB_ENV
          echo "DB_PASS=$(aws ssm get-parameter --name '/DB_PASSWORD' --with-decryption --query 'Parameter.Value' --output text)" >> $GITHUB_ENV
          echo "DB_HOST=$(aws ssm get-parameter --name '/DB_HOST' --query 'Parameter.Value' --output text)" >> $GITHUB_ENV
          echo "DB_NAME=$(aws ssm get-parameter --name '/DB_NAME' --query 'Parameter.Value' --output text)" >> $GITHUB_ENV
          echo "DB_PORT=$(aws ssm get-parameter --name '/DB_PORT' --query 'Parameter.Value' --output text)" >> $GITHUB_ENV

      - name: Save private key to file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Show key file content
        run: |
          cat ~/.ssh/id_ed25519

      - name: Add EC2 to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection with debug logs
        run: |
          echo "Testing SSH connection to EC2 with debug logs..."
          ssh -vvv -i ~/.ssh/id_ed25519 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} exit || true

      - name: Debug SSH Key
        run: |
          ls -lah ~/.ssh/
          cat ~/.ssh/id_ed25519
          ssh-keygen -y -f ~/.ssh/id_ed25519

      - name: Check SSH Private Key
        run: |
          ssh-keygen -y -f ~/.ssh/id_ed25519 || echo "Invalid SSH key!"

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest images..."
            docker pull ngolik/eureka
            docker pull ngolik/api-gateway
            docker pull ngolik/auth-service
            docker pull postgres

            echo "Running docker-compose..."
            DB_USER=${{ env.DB_USER }} \
            DB_PASS=${{ env.DB_PASS }} \
            DB_HOST=${{ env.DB_HOST }} \
            DB_NAME=${{ env.DB_NAME }} \
            DB_PORT=${{ env.DB_PORT }} \
            set -x
            cd /home/ubuntu/auth-service
            sudo docker-compose up -d

