name: Deploy to EC2

on:
  push:
    branches:
      - main  # или твоя основная ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Get DB Credentials from AWS Parameter Store
        run: |
          echo "Fetching DB credentials from AWS Parameter Store..."
          echo "DB_USER=$(aws ssm get-parameter --name "/DB_USER" --with-decryption --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "DB_PASS=$(aws ssm get-parameter --name "/DB_PASSWORD" --with-decryption --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "DB_HOST=$(aws ssm get-parameter --name "/DB_HOST" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "DB_NAME=$(aws ssm get-parameter --name "/DB_NAME" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "DB_PORT=$(aws ssm get-parameter --name "/DB_PORT" --query "Parameter.Value" --output text)" >> $GITHUB_ENV

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest images..."
            docker pull ngolik/eureka
            docker pull ngolik/api-gateway
            docker pull ngolik/auth-service
            docker pull postgres

            echo "Running docker-compose..."
            DB_USER=${{ env.DB_USER }} \
            DB_PASS=${{ env.DB_PASS }} \
            DB_HOST=${{ env.DB_HOST }} \
            DB_NAME=${{ env.DB_NAME }} \
            DB_PORT=${{ env.DB_PORT }} \
            docker-compose up -d
