- name: Save private key to file
  run: |
    mkdir -p ~/.ssh
    echo "${{ secrets.EC2_SSH_KEY_ED25519 }}" | tr -d '\r' > ~/.ssh/id_ed25519
    chmod 600 ~/.ssh/id_ed25519

- name: Add EC2 to known_hosts
  run: |
    ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

- name: Test SSH connection with debug logs
  run: |
    ssh -vvv -i ~/.ssh/id_ed25519 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} exit || true

- name: Deploy to EC2 via SSH
  uses: appleboy/ssh-action@v0.1.0
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY_ED25519 }}
    script: |
      echo "Pulling latest images..."
      docker pull ngolik/eureka
      docker pull ngolik/api-gateway
      docker pull ngolik/auth-service
      docker pull postgres

      echo "Running docker-compose..."
      DB_USER=${{ env.DB_USER }} \
      DB_PASS=${{ env.DB_PASS }} \
      DB_HOST=${{ env.DB_HOST }} \
      DB_NAME=${{ env.DB_NAME }} \
      DB_PORT=${{ env.DB_PORT }} \
      set -x
      cd /home/ubuntu/auth-service
      sudo docker-compose up -d
